### PR TITLE
removed 2x nginx added 1x traefik

### PR DESCRIPTION
**Pull request by ohkeenan**
Gauging interest - it's possible to use 1 container (could have used nginx as well but traefik may be useful for ssl down the line). Let me know what you think :)

http://localhost:8080 for traefik dashboard
http://bobarr.localhost for bobarr webui
http://transmission.localhost for transmission webui
http://jackett.localhost for jackett webui

### CODE REVIEW

**Comment by kleyu** [comment]
This also helps users with ARM devices (rPi 4 arm32v7 in my case, idk about others) by removing the incompatible nginx image.
One thing to modify in my case was to change image from `bitnami/redis` to `arm32v7/redis` here:
https://github.com/iam4x/bobarr/pull/80/files#diff-060ec519a4aedabbb1216288e1e2c7c9R54

related to #41

**Comment by iam4x** [comment]
Hi, thank you very much for the contribution 🙌

I did not know traefik, it looks it suits much better than nginx for bobarr use case.

I'm going to checkout and try your branch later today.

**Comment by iam4x** [comment]
@ohkeenan why did you change the healthcheck to a custom node script?

**Comment by ohkeenan** [comment]
> @ohkeenan why did you change the healthcheck to a custom node script?

When I pulled the images, the alpine-12 docker images didn't come with curl preinstalled so they were failing/unhealthy. Changed to node healthcheck instead of adding curl because it already had node installed and I believe it's a more secure way of health checks. [See here](https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/): since we're not adding an additional package the total container size will be smaller and since we're checking the HTTP response we can tell if the service is actually healthy. Sometimes curl will report healthy because it can curl a page but in your previous curl checks, it's receiving a 302 redirect but still reporting healthy so the api could actually be down.

**Comment by iam4x** [comment]
Okey,  I get your point and this article made me learn something new thank you 👍 

But for simplicy I'll close this PR and keep the discussion and track traefik and wireguard into #83 where we are already discussing :)

**Pull request closed without merging**
