### PR TITLE
fix: Download process start before Jackett finish searching all providers

### PR DESCRIPTION
**Pull request by z7shahriar**
Screenshot at 2020-04-30 23-14-06

### CODE REVIEW

**Comment by iam4x** [comment]
Hi, this is not a bug but a feature.

Some indexers may not work or be very long to return that's why I'm resolving the search as soon we found one matching result from any trackers. This is related to #58 and fixed a bug where download doesn't starts because Jackett is not timing out by itself searches.

If we want something more modular, we might want to add a timeout on trackers search? What do you think?

**Comment by rasoul-shahriari** [comment]
> Hi, this is not a bug but a feature.
> 
> Some indexers may not work or be very long to return that's why I'm resolving the search as soon we found one matching result from any trackers. This is related to #58 and fixed a bug where download doesn't starts because Jackett is not timing out by itself searches.
> 
> If we want something more modular, we might want to add a timeout on trackers search? What do you think
Hi @iam4x: Sure Definitely what you mentioned makes sense, I changed this part of code in my real server and decided to make a pr for others. I will do more research to see what I can do, it's gonna be fun.

**Comment by z7shahriar** [comment]
Hi @iam4x I changed Jackett service based on what we discussed

**Comment by iam4x** [comment]
Hi @z7shahriar thank you,

I think we should extend the timeout to something like ~1-2minutes because sometimes it can be very long before getting a result. And since this run in delayed jobs we are not in a hurry for a result under 5 seconds.

What do you think?

**Comment by z7shahriar** [comment]
Hi @iam4x for the automatic search I put 2 minutes but for the manual search I put 30 seconds, maybe having a timeout in the settings for users to decide it based on network connection would be a good idea.

anyway, the result I get is in Bobarr is so much better than my Radarr setup :)

image

**Comment by iam4x** [comment]
Yes we should add at least a env variable to tweak this easily and it will be good to merge 👍

**Comment by rasoul-shahriari** [comment]
Hi @iam4x I hope I got what you meant correct, I have added env variables

**Comment by iam4x** [comment]
Thank you 👍

**Pull request merged**
