### PR TITLE
Drop nginx container by specifying transmission port

### PR DESCRIPTION
**Pull request by viranch**
... also works with VPN and WireGuard.

### CODE REVIEW

**Comment by iam4x** [comment]
Hey, this is allowing access to the Transmission UI through `http://localhost:9091`

**Comment by viranch** [comment]
I didn't quite understand, is accessing the Transmission UI using `http://localhost:9091` a problem?

**Comment by iam4x** [comment]
https://github.com/dperson/openvpn-client#local-network-access-to-services-connecting-to-the-internet-through-the-vpn

**Comment by viranch** [comment]
You can expose 9091 in the VPN container and use `http://localhost:9091` to access the VPN'd transmission container.

Without VPN, the transmission UI is already accessible at the same URL.

**Comment by iam4x** [comment]
Yes without the VPN it works, but I've tried your configuration and it doesn't work for me without the nginx proxy. On what system are you running bobarr? Do you use something like `--net=host`?

**Comment by viranch** [comment]
You are right, it doesn't seamlessly work with VPN. I am always using a VPN so I simply expose 9091 port from the VPN container to the host. But I can't find a way for both on and off VPN compose files to work out of the box.

I suppose putting `--net=host` for transmission container in `docker-compose.yml` AND exposing 9091 port of the VPN container in wireguard and vpn compose files could work, but I haven't tried it. I think it's worth a shot in the spirit of one less container.

**Pull request closed without merging**
